### ISSUE TITLE
此处是否应该使用has_permission而非has_permission_higher_than

### ISSUE THREAD

**Issue by meng877** [LazyAlienServer/MirrorMcsmcdR#15]
https://github.com/LazyAlienServer/MirrorMcsmcdR/blob/0ba35182136e7bed15dbb14071ba212506b95386/mirror_mcsmcdr/mirror_manager.py#L163

根据readme中的描述,，玩家权限等级不低于config中设置的即可执行
即满足(玩家权限 >= 配置文件) 就能执行
而不是玩家权限需要比config中的等级高(玩家权限 > 配置文件)才可执行

https://docs.mcdreforged.com/zh-cn/latest/code_references/command.html#mcdreforged.command.command_source.CommandSource.has_permission

**Comment by tanhHeng** [comment]
感谢指正，已在 #16 修复
