### ISSUE TITLE
MirrorMcsmcdR无法正常启动，配置文件会被自动重置为开箱状态

### ISSUE THREAD

**Issue by 345111115** [LazyAlienServer/MirrorMcsmcdR#19]
我尝试在我的服务器上运行MirrorMcsmcdR，我遵照快速开始配置了我的config.json和MCSM,但是服务器启动后，config.json的配置会被重置回开箱状态，使用指令会表示需配置MCSM，请问我是做错了那一步，谢谢。附MCRD日志和配置完成的config.json文件
[config.json](https://github.com/user-attachments/files/17891518/config.json).
[MCDR.log](https://github.com/user-attachments/files/17891519/MCDR.log)

**Comment by tanhHeng** [comment]
`uuid` `remote_uuid` `api_key`都要用引号包裹，配置json文件时建议使用VSCode
等文本编辑器，便于检查json格式错误
